
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProjectNghiPhep.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Document
{

    public string C_id { get; set; }

    public string code { get; set; }

    public int status { get; set; }

    public string createdById { get; set; }

    public double createdAt { get; set; }

    public string verifiedById { get; set; }

    public Nullable<double> startDate { get; set; }

    public Nullable<double> endDate { get; set; }

    public string reason { get; set; }

    public Nullable<double> verifiedAt { get; set; }



    public virtual User createdBy { get; set; }

    public virtual User verifiedBy { get; set; }

}

}
