//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectNghiPhep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_permision
    {
        public tbl_permision()
        {
            this.tbl_per_relationship = new HashSet<tbl_per_relationship>();
            this.tbl_permision_detail = new HashSet<tbl_permision_detail>();
        }
    
        public int id_per { get; set; }
        public string name_per { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<tbl_per_relationship> tbl_per_relationship { get; set; }
        public virtual ICollection<tbl_permision_detail> tbl_permision_detail { get; set; }
    }
}
