//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Globalization;
using System.Web.Security;

namespace ProjectNghiPhep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public string C_id { get; set; }
        public string code { get; set; }
        public int status { get; set; }
        public string createdById { get; set; }
        public double createdAt { get; set; }
        public string verifiedById { get; set; }
        [Display(Name = "Ngày bắt đầu")]
        public Nullable<double> startDate { get; set; }
        [Display(Name = "Ngày bắt đầu")]
        public string startDateString { get; set; }
        [Display(Name = "Ngày kết thúc")]
        public Nullable<double> endDate { get; set; }
        [Display(Name = "Lý do")]
        public string reason { get; set; }
        [Display(Name = "Ngày kết thúc")]

        public string endDateString { get; set; }

        [Display(Name = "Số ngày")]
        public string count { get; set; }
        public Nullable<double> verifiedAt { get; set; }
    
        public virtual User createdBy { get; set; }
        public virtual User verifiedBy { get; set; }
    }
}
