//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectNghiPhep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        public NHANVIEN()
        {
            this.tbl_per_relationship = new HashSet<tbl_per_relationship>();
        }
    
        public int MaNV { get; set; }
        public string TenNV { get; set; }
        public string Email { get; set; }
        public string GioiTinh { get; set; }
        public string DiaChi { get; set; }
        public string SDT { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string chucvu { get; set; }
        public string user_name { get; set; }
        public string pass { get; set; }
    
        public virtual ICollection<tbl_per_relationship> tbl_per_relationship { get; set; }
    }
}
