//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectNghiPhep.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Departments = new HashSet<Department>();
            this.Departments1 = new HashSet<Department>();
            this.Documents = new HashSet<Document>();
            this.Documents1 = new HashSet<Document>();
            this.Users1 = new HashSet<User>();
        }
    
        public string C_id { get; set; }
        public string username { get; set; }
        public bool isActive { get; set; }
        public string createdById { get; set; }
        public Nullable<double> createdAt { get; set; }
        public string titleId { get; set; }
        public string departmentId { get; set; }
        public string contractId { get; set; }
        public Nullable<int> dayOff { get; set; }
        public string fullName { get; set; }
        public string address { get; set; }
        public string gender { get; set; }
        public string password { get; set; }
        public Nullable<double> dateOfBirth { get; set; }
        public string email { get; set; }
        public string mobile { get; set; }
    
        public virtual ContractType ContractType { get; set; }
        public virtual ICollection<Department> Departments { get; set; }
        public virtual ICollection<Department> Departments1 { get; set; }
        public virtual Department Department { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<Document> Documents1 { get; set; }
        public virtual Title Title { get; set; }
        public virtual ICollection<User> Users1 { get; set; }
        public virtual User User1 { get; set; }
    }
}
